name: Build and run test files 

on:
  # Triggers the workflow on  pull request events 
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Unit-tests:
    # Use the latest version of Windows as the runner
    runs-on: windows-latest
    timeout-minutes: 60
    
    steps:
      # Checkout the repository to the runner
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Set up the .NET environment
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:        
          # Replace with the desired .NET Core version
          dotnet-version: "6.0.x"       
       
      # Build the solution in the root directory
      - name: Build the solutions
        run: dotnet build 
      
      # Run all the test files in the solution 
      - name: Run tests files
        run: dotnet test --no-restore
          
